# Auto-generated by OpenTofu - Infrastructure values only
# To regenerate: cd opentofu && tofu apply
# 
# IMPORTANT: Service enables (enable_baserow, enable_nocodb, etc.) are NOT auto-generated.
# Add them manually below and they will persist across tofu apply runs.

---
# Infrastructure Configuration (auto-generated)
domain: ${domain}
home_ip: "${home_ip}"

# GitHub Repository (Private)
github_org: ${github_org}
github_repo: ${github_repo}
github_pat: "${github_pat}"

# Server Configuration
username: ${username}
stack_dir: "/home/${username}/stack"

# Services to Enable/Disable (EDIT MANUALLY - not auto-generated)
# To add a new service, add an entry here with enabled, compose_file, subdomain(s), and secrets
services:
  baserow:
    enabled: false
    compose_file: docker-compose.baserow.yml
    subdomain: baserow
    secrets:
      - REDIS_PASSWORD
      - DATABASE_PASSWORD
      - SECRET_KEY
      - BASEROW_S3_SECRET_KEY
  nocodb:
    enabled: false
    compose_file: docker-compose.nocodb.yml
    subdomain: nocodb
    secrets:
      - NOCODB_PASSWORD
  minio:
    enabled: false
    compose_file: docker-compose.minio.yml
    subdomains: [minio, minio-data]
    secrets:
      - MINIO_ROOT_PASSWORD
  postiz:
    enabled: false
    compose_file: docker-compose.postiz.yml
    subdomain: postiz
    secrets:
      - POSTIZ_DB_PASSWORD
      - POSTIZ_JWT_SECRET
  nca_toolkit:
    enabled: false
    compose_file: docker-compose.nca-toolkit.yml
    subdomain: nca-toolkit
    secrets:
      - NCA_API_KEY
      - NCA_S3_ACCESS_KEY
      - NCA_S3_SECRET_KEY
  kokoro_tts:
    enabled: false
    compose_file: docker-compose.kokoro-tts.yml
    subdomain: kokoro-tts
    secrets: []

# DNS Settings
wait_for_dns: true
dns_max_attempts: 60
dns_check_delay: 10
dns_resolver: "1.1.1.1"

# Other Settings
timezone: "UTC"
compose_project: "n8n"
