# Auto-generated by OpenTofu
# To regenerate: cd opentofu && tofu apply

all:
  hosts:
    n8n-server:
      ansible_host: ${server_ip}
      ansible_user: ${username}
      ansible_ssh_private_key_file: ${ssh_key_path}
      ansible_python_interpreter: auto_silent
