# Auto-generated by OpenTofu - DO NOT EDIT
# To regenerate: cd opentofu && tofu apply

---
# Infrastructure Configuration
domain: ${domain}
home_ip: "${home_ip}"

# GitHub Repository (Private)
github_org: ${github_org}
github_repo: ${github_repo}
github_pat: "${github_pat}"

# Server Configuration
username: ${username}
stack_dir: "/home/${username}/stack"

# DNS Settings
wait_for_dns: true
dns_max_attempts: 60
dns_check_delay: 10
dns_resolver: "1.1.1.1"

# Other Settings
timezone: "UTC"
compose_project: "n8n"
